### ISSUE TITLE
Finalize Docs

### ISSUE THREAD

**Issue by PascaleBeier** [PascaleBeier/bootstrap-validate#15]
- [x] Get some time on writing the docs :)
- [x] Add Info for ES6 Environments
- [ ] Add Info on how to Contribute
- [ ] Add Code snippets
- [ ] Add more usage examples; ideally of every rule and real world examples

**Comment by richardproxy** [comment]
Two questions, maybe two requirements:)))
1. Is there a convenient way to  disable button "Submit" when there is a invalid input. And after all invalid inputs are correct,  enable the "Submit" button. I know there is callback function, but if there are too many input components , the error status is not easy to manage. 
2. Is there a way use Submit action to  run all validater rules. You project is really useful, maybe it's time to write more document and example.

**Comment by richardproxy** [comment]
I am just a server side programmer, i am not familiar with JS.  I think current version is really simple, easy to understand.  Hope you keep your project simple and "stupid" :))))

**Comment by PascaleBeier** [comment]
Well, I am as well. :)

That's the Challenge keeping it simple!

richardproxy <notifications@github.com> schrieb am Mo., 7. Mai 2018, 16:38:
