### ISSUE TITLE
Support Bootstrap 4

### ISSUE THREAD

**Issue by PascaleBeier** [PascaleBeier/bootstrap-validate#17]
Since the first Bootstrap 4 Beta shipped bootstrap-validate should support the latest branch.

**Comment by PascaleBeier** [comment]
Support for Bootstrap v4 will happen in the 2.x branch

**Comment by MilenFrom** [comment]
Hi,

Any luck with this, does it support Bootstrap 4 yet?

**Comment by PascaleBeier** [comment]
It does not yet!

I look forward releasing it within the next days.

**Comment by MilenFrom** [comment]
Thank you very much for the quick reply.
Looking forward for this.

Great work, awesome validator!

**Comment by PascaleBeier** [comment]
Done with v2 in https://github.com/PascaleBeier/bootstrap-validate/commit/5f4e21ab8f4eca55589edcac81a5f023b1136d5c
