### ISSUE TITLE
matches rule returns "o.default[e[0]] is undefined"

### ISSUE THREAD

**Issue by lhoekenga** [PascaleBeier/bootstrap-validate#19]
The "matches" rule returns an undefined error.
bootstrap-validate 1.0.11, bootstrap 3.3.7

**html**
`<div class="form-group">`
`    <label for="inputMatch1" class="control-label col-sm-2">type some stuff</label>`
`    <div class="col-sm-10">`
`      <input id="inputMatch1" type="text" class="form-control">`
`    </div>`
`    <label for="inputMatch2" class="control-label col-sm-2">type the same stuff</label>`
`    <div class="col-sm-10">`
`      <input id="inputMatch2" type="text" class="form-control">`
`    </div>`
`  </div>`

**javascript**
`  bootstrapValidate(
    '#inputMatch2',
    'matches:#inputMatch1:type the text from the callback test'
  );`

**Comment by PascaleBeier** [comment]
Nice catch!

The matches rule should have been added in v1.1.0 and made its way in v2. I will push another release for Bootstrap 3 ASAP.

**Comment by PascaleBeier** [comment]
Fixed, please grab the latest version for Bootstrap 3 here:

https://github.com/PascaleBeier/bootstrap-validate/releases/tag/1.1.0
