### ISSUE TITLE
Validate all fields in form while add rule to one field

### ISSUE THREAD

**Issue by quannv** [PascaleBeier/bootstrap-validate#23]
All field in the form

`
bootstrapValidate('#address_from', 'rule', function (isValid) {
		   if (isValid) {
			//do something
		   } else {
		       alert('Not valide');
		       return false;
		   }
		});
`

**Comment by PascaleBeier** [comment]
This is possible:

If you want to apply the same validation rules to multiple input elements, you can pass an Array of selectors:

`bootstrapValidate(['#prename', '#lastname'], 'max:20:Enter no more than 20 characters!');`

The additional maintenance cost of automagically validate all fields wouldnt be worth it.
