### ISSUE TITLE
Regex Issue when using :

### ISSUE THREAD

**Issue by enkota** [PascaleBeier/bootstrap-validate#26]
I am using the following regex

`bootstrapValidate('#inputfield', 'regex:/^(my:track:[a-zA-Z0-9]{22}$)/:Invalid')`

The issue is I am using `:` inside the regex match which conflicts with the separator options.

How can I stop the `:` regex conflicting? Thanks!

**Comment by PascaleBeier** [comment]
Fixed in https://github.com/PascaleBeier/bootstrap-validate/commit/68a23a5bd9a6d02444d91b3d43fd9dae10bb673b (v2.1.3), check out https://github.com/PascaleBeier/bootstrap-validate/blob/master/__tests__/integration/regex.html for usage of your regex.
