### ISSUE TITLE
Form submits with errors

### ISSUE THREAD

**Issue by IbrahimTareq** [PascaleBeier/bootstrap-validate#29]
Currently, the form submits even when there are errors present. Is there a way to check for errors before submitting the form?

**Comment by PascaleBeier** [comment]
This is planned! 

Currently, you can look for the CSS classes bootstrap-validate adds to errornous form inputs and disable the submit button with JavaScript.

**Comment by IbrahimTareq** [comment]
Very hacky but it should do for now. Thanks mate!

**Comment by PascaleBeier** [comment]
Thats exactly how the library would do it :p

**Comment by rostamiani** [comment]
Required rule is not checked initially. then there is no error classes there yet!
