### ISSUE TITLE
Usage with Angular

### ISSUE THREAD

**Issue by MarvinMogab** [PascaleBeier/bootstrap-validate#31]
How should I call the bootstrapValidate function in Angular CLI ? Angular will not allow the calling of script tags inside the template of component.

**Comment by PascaleBeier** [comment]
Since you already use a module bundler, you don't need any additional script tags:

You can import bootstrapValidate into your app like this: (ES6)
```javascript
import * as bootstrapValidate from 'bootstrap-validate';
window.bootstrapValidate = bootstrapValidate;
```

Then you can just call the `bootstrapValidate` object like you would in a script tag, e.g:

```javascript
// [...]
bootstrapValidate('#email', 'email:Enter a valid Mail address');
```
