### ISSUE TITLE
Regex File Type

### ISSUE THREAD

**Issue by Joshong1991** [PascaleBeier/bootstrap-validate#33]
Doesn't work  
**Rule I apply :** "regex:(xlsx|png)+$:Please upload xlsx file !"
Uncaught TypeError: Cannot read property 'apply' of undefined

This work
**Rule I apply :** "regex:(xlsx)+$:Please upload xlsx file !"

Any solution ?

**Comment by PascaleBeier** [comment]
That is because your regex contains a |.

But for your use case try using the endsWith rule, which might work for files.

Keep me updated

**Comment by Joshong1991** [comment]
endswith only able validate one file type.
could I validate multiple file type ?

Thank You.

**Comment by PascaleBeier** [comment]
You could use two endsWith rules

Joshong1991 <notifications@github.com> schrieb am Fr., 13. Juli 2018, 11:31:

**Comment by PascaleBeier** [comment]
How did you end up solving that issue?
