### ISSUE TITLE
match rule doesn't update if matches: field is changed instead of input field

### ISSUE THREAD

**Issue by jasonmixed** [PascaleBeier/bootstrap-validate#37]
How to replicate the problem:
2 Fields: LogonID1, LogonID2
Code: 
`bootstrapValidate('#LogonID2', 'matches:#LogonID1: Logon IDs do not match.');`

User will input a username in LogonID1 field incorrectly 'user123', then input correct username 'user1234' into LogonID2. User will then update LogonID1 field to 'user1234' and the error message will not go away.

**Comment by radioactiveboyx** [comment]
same problem here did oyu fix it?
