### ISSUE TITLE
How to check validation?

### ISSUE THREAD

**Issue by bar15150** [PascaleBeier/bootstrap-validate#38]
How can I check if the validation is true?

Only adding 
```
bootstrapValidate('.form-control.email', 'required|email:Enter a valid E-Mail!');
```
Is not enough. I need something like (I have to prevent the default form submit or check before an ajax request):

```
if (bootstrapValidate.allValidationsAreTrue()) {
...
}
```

**Comment by PascaleBeier** [comment]
You can look for the existance of any error classes on the form submission event :)

Currently on mobile, but its alike of

```javascript
document.getElementById('myform').addEventListener('submit', function (e) {

  e.preventDefault();
  if (document.querySelector('.has-error') {
    alert('Fix form errors first');
  }
});
```
