### ISSUE TITLE
How difficult would be to add a Numeric Range option?

### ISSUE THREAD

**Issue by orware** [PascaleBeier/bootstrap-validate#40]
Hi there,

I have a form I'm working on which requires a numeric range so I think currently the regex option is probably the only route for me to go but I feel like the website may need some more examples since the regex I have doesn't seem to be working as expected.

So I was hoping maybe to make the overall process easier, if there was a new numeric range option where users could provide both min and max values (and enable floating point or just require integers) that would meet my needs currently.

Another quick note is that if I have a field set to be required, but that message does not appear if I load the page and quickly hit submit...it only appears when I type something in and then use backspace and erase everything.

Thank you for your work on this :-)!

**Comment by PascaleBeier** [comment]
Thanks for your kind words. We could actually extend the existing min / max rules to accept floating point numbers, since we use a library for arithmetic precision anyways.

**Comment by PascaleBeier** [comment]
I advise you to use https://github.com/jquery-validation/jquery-validation, since I'm not working on bootstrap-validate in the near future (or, ever, but who knows)
