### ISSUE TITLE
Change to 'is-valid' class

### ISSUE THREAD

**Issue by malmr** [PascaleBeier/bootstrap-validate#41]
Hello,
 after validation it would be perfect to change the input class from: _is-invalid_  to _is-valid_.
This would stylize the input border color from red to green. At the moment it just removes the _is-invalid_, which utter in a red border-color changing to default input border.
Thanks, malmr

**Comment by PascaleBeier** [comment]
Good idea!

**Comment by PascaleBeier** [comment]
Hey again @malmr 

I advise you to use https://github.com/jquery-validation/jquery-validation, since I'm not working on bootstrap-validate in the near future (or, ever, but who knows)

**Comment by SoyDiego** [comment]
> I advise you to use https://github.com/jquery-validation/jquery-validation, since I'm not working on bootstrap-validate in the near future (or, ever, but who knows)

@PascaleBeier It's a pity that you do not continue this project and implement new things, it's really amazing and very useful. I hope you continue with him. Congratulations and thanks!
