### ISSUE TITLE
bootstrapValidate

### ISSUE THREAD

**Issue by qayyumabro** [PascaleBeier/bootstrap-validate#44]
https://imghostr.com/aGdsmDac

jquery-3.3.1.min.js:2 Uncaught ReferenceError: bootstrapValidate is not defined
    at HTMLDocument.<anonymous> (signup:207)
    at l (jquery-3.3.1.min.js:2)
    at c (jquery-3.3.1.min.js:2)

**Comment by PascaleBeier** [comment]
1. Provide some Code :)
2. You must not use jquery selectors
3. A jquery plugin nicht be the best for you
