### ISSUE TITLE
Call validation on click

### ISSUE THREAD

**Issue by GidanMX2** [PascaleBeier/bootstrap-validate#46]
Missing a method to trigger validation by clicking on a button, ie:

function checkFormSubmit(){
bootstrapValidate('#tbEmail').validate();
}

**Comment by dominicklee** [comment]
Using a function like this, you can trigger the validation:
```html
function checkElement(selector)
{
	const myElement = document.getElementById(selector);
	myElement.dispatchEvent(new Event("input"));
}
```
