### ISSUE TITLE
Is it possible to add an Ajax check before submitting the form?

### ISSUE THREAD

**Issue by roushenas** [PascaleBeier/bootstrap-validate#47]
Hi there,
In addition to client-side validation (which you did nicely), I want to add another step to validate the input on the server. As an example, suppose I wanna check for an email as username.
The first step would be checking the email format (browser side), and if the email format was correct, I wanna send the field value to the server (without pressing on submit button - it should be done as the next step of validation), to make sure this email was not taken before.
Can you tell me how to implement this feature?

**Comment by PascaleBeier** [comment]
This is currently not possible. Rather checkout jquery-validation.
