### ISSUE TITLE
NPM module updated?

### ISSUE THREAD

**Issue by simplenotezy** [PascaleBeier/bootstrap-validate#48]
I notice when pulling in bootstrap-validate using `yarn add bootstrap-validate` I get version `2.1.3` but as per [documentation](https://bootstrap-validate.js.org/), latest version seems to be: 2.2.0

      <script src="https://cdn.rawgit.com/PascaleBeier/bootstrap-validate/v2.2.0/dist/bootstrap-validate.js" ></script>

**Comment by simplenotezy** [comment]
Seems v 2.2.0 is missing from https://www.npmjs.com/package/bootstrap-validate

**Comment by simplenotezy** [comment]
Switched to [jquery-validate](https://jqueryvalidation.org) after seeing readme ("Not really mainained!")

**Comment by PascaleBeier** [comment]
Thanks for the hint, I just published v2.2.0 on npm.
