### ISSUE TITLE
validation rule with multiple values (like cc) throws error

### ISSUE THREAD

**Issue by jskowalski** [PascaleBeier/bootstrap-validate#50]
^4[0-9]{12}(?:[0-9]{3})?$ works
^(?:4[0-9]{12}(?:[0-9]{3})?|5[1-5][0-9]{14})$ does not

**Comment by PascaleBeier** [comment]
Because of the pipe operator. "|" is used as rule separator.

**Comment by PascaleBeier** [comment]
Reopening due to upcoming Regex changes

**Comment by PascaleBeier** [comment]
See #57
