### ISSUE TITLE
Major issue!

### ISSUE THREAD

**Issue by iLinked1337** [PascaleBeier/bootstrap-validate#54]
Hello, today i was trying out your library, when i encountered this error: 
```
Uncaught TypeError: Cannot read property 'addEventListener' of null
    at C:\Users\ilink\source\repos\BotBuilder\Frontend\node_modules\bootstrap-validate\dist\bootstrap-validate.js:1
    at Array.forEach (<anonymous>)
    at t.exports (C:\Users\ilink\source\repos\BotBuilder\Frontend\node_modules\bootstrap-validate\dist\bootstrap-validate.js:1)
    at buildInstructionArgs (instructions.js:30)
    at getInstructionTypes (addinstruction.html:71)
    at addinstruction.html:12
```

This confuses me because i've already created the element with javascript, and it has been given an ID.
For some context i'm also using electron.js.

If anyone has had this issue and have fixed it, please tell me!

Thanks in advanced,
iLinked

**Comment by PascaleBeier** [comment]
Hey there,

the package should only work in the rendering context. Can't think of another reason why it shouldn't work in electron.
