### ISSUE TITLE
Regex problems

### ISSUE THREAD

**Issue by ezramod** [PascaleBeier/bootstrap-validate#55]
Hello how can i add this regex for validate?
^(\+4|)?(07[0-8]{1}[0-9]{1}|02[0-9]{2}|03[0-9]{2}){1}?(\s|\.|\-)?([0-9]{3}(\s|\.|\-|)){2}$

**Comment by tingus** [comment]
The guy does not support this anymore. It's a shame as I had to remove it from a project.

**Comment by PascaleBeier** [comment]
Sorry, I do not seem to get notified anymore. I will look into this if it doesnt work with the regex rule.

**Comment by PascaleBeier** [comment]
@ezramod https://regex101.com/ tells me that the regex is not valid, can you provide more information on what you want to achieve?

**Comment by PascaleBeier** [comment]
See #57
