### ISSUE TITLE
Password Validation

### ISSUE THREAD

**Issue by josiahking** [PascaleBeier/bootstrap-validate#56]
It will be great to have this plugin handle password validation too.

Thank you for the good work.

**Comment by PascaleBeier** [comment]
What exactly do you need? You can chain the existing rules to achieve some arbitrary password validation like minimum length.

**Comment by josiahking** [comment]
Something like strong password validation.

**Comment by dominicklee** [comment]
@josiahking In case you are still looking for a solution:

The recommended criteria for a strong password is one that has:
- 8 or more characters
- At least one uppercase letter
- At least one lowercase letter
- At least one digit
- At least one special character

Let's assume your password field has an ID called `password`. 
Using the bootstrap-validate library, you can achieve this as follows:

```html
bootstrapValidate('#password', 'min:8:Must be 8 or more characters|regex:^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).*$:Must contain 1 upper and lower case, number, and special character');
```
