### ISSUE TITLE
Regex Rule cannot handle all Expressions

### ISSUE THREAD

**Issue by PascaleBeier** [PascaleBeier/bootstrap-validate#57]
Because of how this library handles regex (as a string, that is), not all regular expressions work.

Keep in mind that you leave out the Quanitifiers "/" "/g" etc and check your own regexes for JavaScript at regex101.

**Comment by VegaMex** [comment]
Seems like it has many problems with complex regex. I'm trying to validate with these regex:

For a simple name (example: Oscar):
`/[ÁÉÍÓÚÑA-Z][a-záéíóúñ]+(\s+[ÁÉÍÓÚÑA-Z]?[a-záéíóúñ]+)*$/g`

For a password (example: Abc12#45)
`/^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#$%^&*])[0-9a-zA-Z!@#$%^&*]{8,}$/g`

And is not working! :(

**Comment by PascaleBeier** [comment]
@VegaMex 

Your first regex works:

https://jsfiddle.net/57pyawLn/4/

Keep in mind you are using JavaScript. Please validate your Regex! :) A good tool is regex101.

**Comment by VegaMex** [comment]
@PascaleBeier 

I really needed the quantifiers, and the second one only works without the quotes, but if the library uses strings there's nothing to do. Thanks for reply.

**Comment by PascaleBeier** [comment]
see #65
