### ISSUE TITLE
Custom validation function

### ISSUE THREAD

**Issue by aksamit** [PascaleBeier/bootstrap-validate#58]
A powerful tool would be to enhance the interface with the ability to link the validation to a custom callback function where a user could implement a more advanced validation algorithm. 

I stumbled upon a situation where I need to validate Australian Business Number (ABN) (https://abr.business.gov.au/Help/AbnFormat), most other country-specific numbers I can validate with the regex or other built-in rules of bootstrap.js, but now at a dead end when I needed to add support for ABN.

**Comment by PascaleBeier** [comment]
Great Idea.

**Comment by PascaleBeier** [comment]
@aksamit would an ABN rule help you? Implementing custom rules takes some time.

**Comment by aksamit** [comment]
It would be helpful, but I also foresee a need for GLN number validation (https://en.wikipedia.org/wiki/Global_Location_Number) and got some more incoming that I owuld not be able to handle with regex. 

But if you do the ABN in an isolated commit, then perhaps I could help you with GLN and other I have in mind and create pull requests for you?

**Comment by PascaleBeier** [comment]
Well, it really just works with Regular Expressions, just like the Email Rule:

https://github.com/PascaleBeier/bootstrap-validate/blob/master/src/rules.js#L32

I would add tests and search for the proper regexes in each case. Won't be too difficult, I will see if I find some time.

**Comment by aksamit** [comment]
Since these validations include calculations, wouldn't it be tricky to do it with regex? 

https://stackoverflow.com/questions/945763/mod-11-check-digit-with-regex

**Comment by PascaleBeier** [comment]
Fair point, haven't looked at GLN yet.

**Comment by PascaleBeier** [comment]
see #65
