### ISSUE TITLE
How can I show errors when pressing a submit button?

### ISSUE THREAD

**Issue by arce701** [PascaleBeier/bootstrap-validate#59]
I love the library. I just can't find the way to show me the error messages, when they don't comply with the rules, when I press a submit button.

**Comment by arce701** [comment]
I need it to validate me when I am typing in the field and I also need it to validate me when I press the submit button, it shows errors of the fields that do not comply with the rules

**Comment by danilooviedo** [comment]
Please help! I have a same problem...

**Comment by PascaleBeier** [comment]
see #65
