### ISSUE TITLE
How to make the error go away>

### ISSUE THREAD

**Issue by ghost** [PascaleBeier/bootstrap-validate#62]
Hi Pascal!

Let me start by saying I'm a complete newbie, so bear with me... ;) 

I was able to make it work for a URL so it shows the error until the URL is valid, now the issue is that if I decide to delete whatever I put there and leave the field empty, the error message doesn't go away.
On my website, having a URL submitted by the user is not required, but if they decide not to include a URL (after they started typing something), they will still see the error message. Hope it makes sense...

Is there a way to fix this?

![Screen Shot 2020-09-10 at 11 04 12 PM](https://user-images.githubusercontent.com/60773713/92813863-00bbdd80-f3ba-11ea-8c79-7904023241eb.png)

Thank you!

**Comment by PascaleBeier** [comment]
see #65
