### ISSUE TITLE
Is there a chance the new options could be added on bootstrap 3 version of the validator (like regex and field match)?

### ISSUE THREAD

**Issue by logion7** [PascaleBeier/bootstrap-validate#64]
These functions would help a lot of folks that can't make the transition from bootstrap 3 to 4 in their projects. Anyway, thanks for this nice tool!

**Comment by PascaleBeier** [comment]
TBH this project is rather unmaintained except from individual paid requests :(

**Comment by PascaleBeier** [comment]
see #65
