### ISSUE TITLE
Rule Wishlist

### ISSUE THREAD

**Issue by PascaleBeier** [PascaleBeier/bootstrap-validate#9]
- [ ] before(date, dateFormat)
- [ ] after (date, dateFormat)
- [ ] date(format)
- [x] regexp(regexp)
- [ ] phone (format)
- [ ] file(extension)
- [x] divisible (https://github.com/PascaleBeier/bootstrap-validate/issues/9#issuecomment-384778411)
- [x]  url
URL Validation
- [x]  matches
Two fields that should match, e.q. for password confirmations. The v1 API makes that super fuzzy.
- [x]  endswith(string)
Ensure a given string ends with a given string
- [x] startswith(string)
Same as above but starting with
- [x] contains(string)

**Comment by PascaleBeier** [comment]
url added in https://github.com/PascaleBeier/bootstrap-validate/commit/95237a0bf9bbb27b8687952c4fa85b4375e311e1

**Comment by PascaleBeier** [comment]
contains added in https://github.com/PascaleBeier/bootstrap-validate/commit/3913b9ac8e132e27d440843f994a9028f37a56d3

**Comment by PascaleBeier** [comment]
startsWith added in fff8678

**Comment by PascaleBeier** [comment]
endsWith added in aa51798

**Comment by PascaleBeier** [comment]
matches added in 208a5cf

**Comment by PegWeb** [comment]
Password strength? Say being able to specify for example must contain letter number uppercase lower case symbol and so on.

**Comment by PascaleBeier** [comment]
I can surely add uppercase, lowercase and special char Rules which one
could combine!

Am 10.03.2018 00:59 schrieb "Patrick" <notifications@github.com>:

**Comment by PascaleBeier** [comment]
Have a look at src/rules and tests, should be easy to implement If you
wanna give it a shot

Am 10.03.2018 01:28 schrieb "Pascale Beier" <mail@pascalebeier.de>:

**Comment by niladam** [comment]
It would be nice to have a `startsWithOr(1,2)` which will allow you to specify that it needs to start with either 1 or 2..

**Comment by PascaleBeier** [comment]
@niladem cool idea!

I could do that for any rule with n additional arguments. Definitely doing that.

**Comment by StefCoene** [comment]
And I also need an other rule. I need to match a field so the date is in the format YYYY-MM-DD.
Matching the general format is enough. So MM > 13 is allowed.
Maybe it can be a general regexp so it's usable in other situations?


Stef

**Comment by PascaleBeier** [comment]
Hey Stef,

Worthy suggestions! Feel free to send a PR. I'm short on freetime atm.

**Comment by StefCoene** [comment]
I'm working on a new bootstrap 4 project and we need to do some input validation. Your code seems the only form validation code that works with bootstrap 4.
But we are missing some rules. It's not really urgent because the project is still in development state. So take your time.

Stef

**Comment by PascaleBeier** [comment]
@StefCoene Check out v2.1.0

**Comment by niladam** [comment]
Hey @PascaleBeier how about this ? (please keep in mind that my programming skills aren't how i'd like them to be)

```javascript
  startsWithOr: (input, string, string2) => {
    /**
     * @since 2.1.1
     * @param string string: String the input value should start with
     * @param string2 string: Second string the input value should start with
     * @example 1,2
     * @error Your input should contain either 1 or 2.
     * @description Require the input value to start with a given string
     * or a different string.
     */
    // Check first string
    let istrue = false;
    if ( startsWith(input.value, string) ) {
        istrue = true
    }
    if ( startsWith(input.value, string2) ) {
        istrue = true
    }
    return istrue;
},
```

**Comment by niladam** [comment]
I think it would be safe to verify if there are 2 strings in the function, and if not, basically just run startsWith on it. If there are 2 strings, than they'd both need to be verified..

**Comment by PascaleBeier** [comment]
Hey @niladem,

The reason I didnt implement it yet is that I want to find a solution to dynamically add these ...Or-Rules. Will look at that again these days.

Your Code is nice! You could also use the or Operator :)

**Comment by StefCoene** [comment]
Cool, thanks for the quick response!

For the divisible, I also need to check if something is divisible by 0.2. 
For instance, 3.1 % 0.2: false, 4.2 % 0.2: true
I think this should do the trick:

    if ( number < 1 ) {
      return Number(input.value / number) % 1 === 0;
    } else { 
      return Number(input.value) % number === 0;
    }

**Comment by PascaleBeier** [comment]
@StefCoene TIL that % is no modulo operator but a remainder operator per definition in JavaScript 🛩 

Should have tested that more thorough!

Fixed in https://github.com/PascaleBeier/bootstrap-validate/commit/d58f8e0dc3fcce6d605a63c9fbbfab9544aff5d4

**Comment by StefCoene** [comment]
Allmost there :)
3.1 is not divisible by 0.2 but your code accepted this as valid.
Other settings are also not working. I checked your code but couldn't find the error.


Stef

**Comment by PascaleBeier** [comment]
See tests/integration/divisible, 3.1 is definitely not accepted with 0.2. Just tested it. One thing is that an empty string equals 0 which equals to true. 

See: https://jsfiddle.net/57pyawLn/

**Comment by StefCoene** [comment]
Try 3.8 in your fiddle.......

Stef

**Comment by PascaleBeier** [comment]
Loving it!

Viele Grüße aus Herten,
Pascale Beier

Mühlenstraße 57
45701 Herten
02366 / 407 1347
mail@pascalebeier.de
https://pascalebeier.de

2018-05-04 23:29 GMT+02:00 StefCoene <notifications@github.com>:

**Comment by PascaleBeier** [comment]
Seems to be a floating point error:

> 4.6 / 0.2
> 22.999999999999996
